ALTER TABLE public.scans 
ADD COLUMN IF NOT EXISTS judgment_level INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS cuddle_o_meter INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS derp_factor INTEGER DEFAULT 0;
