import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Terms of Service — PawVibe",
    description: "PawVibe terms of service and conditions of use.",
};

export default function TermsPage() {
    return (
        <div className="pt-28 pb-20 px-6">
            <div className="max-w-3xl mx-auto">
                <h1 className="text-4xl md:text-5xl font-black mb-2">
                    <span className="text-[#FFD700]">Terms</span> of Service
                </h1>
                <p className="text-[#8B7BA8] mb-12">Last updated: March 2, 2026</p>

                <div className="space-y-8 text-[#D3C4E5] leading-relaxed">
                    <section>
                        <h2 className="text-2xl font-bold text-white mb-3">1. Acceptance of Terms</h2>
                        <p>By downloading, installing, or using PawVibe (&quot;the App&quot;), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the App.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-3">2. Description of Service</h2>
                        <p>PawVibe is an AI-powered mobile application that analyzes pet photos to determine their mood and emotional state. The analysis results are generated by artificial intelligence and are intended for entertainment purposes only. They should not be considered professional veterinary advice.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-3">3. User Accounts</h2>
                        <p>The App creates anonymous sessions automatically upon first use. No registration or personal information is required. Each anonymous session is unique and tied to your device. If you uninstall the app or clear its data, your session and scan history may be lost.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-3">4. Free & Premium Services</h2>
                        <ul className="list-disc list-inside space-y-2 text-[#8B7BA8]">
                            <li><span className="text-[#D3C4E5]">Free Tier:</span> Users receive 5 free scans per week, which reset automatically every 7 days.</li>
                            <li><span className="text-[#D3C4E5]">Credit Packs:</span> Users may purchase additional scan credits (Snack Pack: 10 scans, Party Pack: 50 scans). Credits do not expire.</li>
                            <li><span className="text-[#D3C4E5]">Premium Subscription:</span> Provides unlimited scans, pet astrology charts, monthly psychological reports, and watermark-free result cards.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-3">5. In-App Purchases & Subscriptions</h2>
                        <ul className="list-disc list-inside space-y-2 text-[#8B7BA8]">
                            <li>All purchases are processed through Apple App Store or Google Play Store.</li>
                            <li>Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current period.</li>
                            <li>You can manage or cancel your subscription in your device&apos;s App Store or Google Play settings.</li>
                            <li>Refunds are handled according to Apple&apos;s or Google&apos;s refund policies.</li>
                            <li>Consumable credits (Snack Pack, Party Pack) are non-refundable once used.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-3">6. Acceptable Use</h2>
                        <p className="mb-3">You agree not to:</p>
                        <ul className="list-disc list-inside space-y-2 text-[#8B7BA8]">
                            <li>Use the App for any unlawful purpose</li>
                            <li>Attempt to reverse engineer, modify, or hack the App</li>
                            <li>Upload inappropriate, offensive, or harmful content</li>
                            <li>Abuse the free credit system through multiple accounts or devices</li>
                            <li>Interfere with the proper functioning of the App</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-3">7. AI-Generated Content Disclaimer</h2>
                        <p>All mood analyses, astrology charts, and monthly reports are generated by artificial intelligence for entertainment purposes. These results do not constitute professional veterinary, medical, or behavioral advice. If you have concerns about your pet&apos;s health or behavior, please consult a qualified veterinarian.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-3">8. Intellectual Property</h2>
                        <p>The App, including its design, code, AI models, branding, and content, is the intellectual property of Setifera. You may share your scan result cards for personal, non-commercial use.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-3">9. Limitation of Liability</h2>
                        <p>PawVibe is provided &quot;as is&quot; without warranties of any kind. We are not liable for any damages arising from your use of the App, including but not limited to: inaccurate AI analysis results, loss of scan history, or service interruptions.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-3">10. Changes to Terms</h2>
                        <p>We reserve the right to modify these Terms at any time. Continued use of the App after changes constitutes acceptance of the new Terms.</p>
                    </section>

                    <section>
                        <h2 className="text-2xl font-bold text-white mb-3">11. Contact</h2>
                        <p>For questions about these Terms, contact us at:</p>
                        <p className="mt-2">
                            <a href="mailto:info@setifera.com" className="text-[#FF007F] hover:underline font-semibold">info@setifera.com</a>
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
}
