ALTER TABLE public.scans
ADD COLUMN IF NOT EXISTS explanation TEXT,
ALTER COLUMN chaos_score DROP NOT NULL,
ALTER COLUMN chaos_score SET DEFAULT 0,
ALTER COLUMN energy_level DROP NOT NULL,
ALTER COLUMN energy_level SET DEFAULT 0,
ALTER COLUMN sweetness_score DROP NOT NULL,
ALTER COLUMN sweetness_score SET DEFAULT 0,
ALTER COLUMN judgment_level DROP NOT NULL,
ALTER COLUMN cuddle_o_meter DROP NOT NULL,
ALTER COLUMN derp_factor DROP NOT NULL;
